### ISSUE TITLE
AttributeError: 'datetime.date' object has no attribute 'date'

### ISSUE THREAD

**Issue by almereyda** [ebridges/accounting-reports#1]
When running the `balances` command, an error is thrown. This is similar to https://github.com/henriquebastos/gnucash-to-beancount/issues/11

A suggestion would be to implement a similar fix.

**Comment by ebridges** [comment]
Thank you for raising this issue.  Do you happen to have an error message that you can provide (as was done in the issue you referenced)?  That will tell me where the error is occurring in this project.
